FROM php:5.5-apache

# PHP extension installation helper
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /bin/
RUN chmod +x /bin/install-php-extensions

# install PHP extensions
RUN bash install-php-extensions bcmath gd mysqli json_encode