services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
      additional_contexts:
        app: docker-image://xnova:dev
    volumes:
      - ./:/var/www/html
    ports:
      - 127.0.0.1:8080:80
    networks:
      - internal
    depends_on:
      - db

  db:
    image: mariadb:lts
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
